require 'nike_v2/version'

require 'httparty'
require 'forwardable'
require 'alchemist'
require 'ext/core_ext'

require 'nike_v2/base'
require 'nike_v2/metric'
require 'nike_v2/metrics'
require 'nike_v2/experience_type'
require 'nike_v2/resource'
require 'nike_v2/person'
require 'nike_v2/activity'
require 'nike_v2/activities'
require 'nike_v2/summary'
require 'nike_v2/gps_data'